In [1]:
import numpy as np

Understanding of 1D, 2D and 3D array in numpy

In [2]:
arr = np.array([1, 3, 4, 7, 9])

In [3]:
arr

array([1, 3, 4, 7, 9])

In [4]:
type(arr)

numpy.ndarray

In [13]:
arr.ndim

1

In [15]:
arr.shape

(5,)

In [5]:
arr2 = np.array([[1, 3], [4, 7]])

In [6]:
arr2

array([[1, 3],
       [4, 7]])

In [7]:
type(arr2)

numpy.ndarray

In [16]:
arr2.shape

(2, 2)

In [12]:
arr2.ndim

2

In [8]:
arr3 = np.array([[[1, 3], [4, 7]], [[2,4],[5,7]]])
arr3

array([[[1, 3],
        [4, 7]],

       [[2, 4],
        [5, 7]]])

In [9]:
type(arr3)

numpy.ndarray

In [11]:
arr3.ndim

3

In [14]:
arr3.shape

(2, 2, 2)

In [18]:
arr4 = np.array([[[1, 3], [4, 7]], [[2,4],[5,7]], [[2,6],[4,7]]])
arr4

array([[[1, 3],
        [4, 7]],

       [[2, 4],
        [5, 7]],

       [[2, 6],
        [4, 7]]])

In [19]:
arr4.shape

(3, 2, 2)

Difference between the functionalities of arange and linspace function in numpy

In [20]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [23]:
np.linspace(1,9,5)

array([1., 3., 5., 7., 9.])

Difference between the shallow copy and deep copy in numpy

In [24]:
arr2

array([[1, 3],
       [4, 7]])

In [25]:
shallowArr = arr2

In [26]:
deepArr = np.copy(arr2)

In [27]:
arr2[0][0] = 5
arr2

array([[5, 3],
       [4, 7]])

In [28]:
shallowArr

array([[5, 3],
       [4, 7]])

In [29]:
deepArr

array([[1, 3],
       [4, 7]])

fromfunction in numpy

In [30]:
np.fromfunction(lambda i,j:i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [31]:
np.fromfunction(lambda i,j:i+j, (4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [32]:
np.fromfunction(lambda i,j:i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

To create an identity matrix

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Reshape function in numpy

In [34]:
dataset = np.linspace(2,9,50)

In [35]:
dataset

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
       4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
       4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143,
       5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
       6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
       7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [37]:
dataset.shape

(50,)

In [38]:
dataset.reshape(2,1,25)

array([[[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
         2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
         3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
         4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
         4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143]],

       [[5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
         6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
         7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
         7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
         8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]]])

In [40]:
dataset.reshape(2,1,25)

array([[[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
         2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
         3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
         4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
         4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143]],

       [[5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
         6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
         7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
         7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
         8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]]])